### ISSUE TITLE
当编辑内容时，为啥一输入内容就关闭了弹窗呢，只能输入一个字母就秒消失

### ISSUE THREAD

**Issue by lzk66688** [zymbth/Editable_table#30]
![image](https://github.com/user-attachments/assets/705e50bd-8f77-4755-b9a8-d22696efee27)

**Comment by zymbth** [comment]
我[在线](https://zymbth.github.io/editable-table/#/edit-tb-v2)试了下没问题啊，可能是鼠标移到输入法上去了？或者是浏览器上装了什么插件导致的？可以拉下代码，本地调试一下，这里监听的[mouseleave](https://github.com/zymbth/editable-table/blob/master/src/views/editable-table-v2.vue#L62-L66)事件

**Comment by zymbth** [comment]
我测试了下，有这些操作会触发隐藏：

![editable-table-bug](https://github.com/user-attachments/assets/902a151f-d3d8-4209-8c8e-6b427d1d9dfd)

**Comment by lzk66688** [comment]
这种情况应该是不对的吧，输入文字就不行，这个隐藏应该是用户写好之后，点击空白或者其他操作，才会更新数据然后隐藏吧。

**Comment by zymbth** [comment]
没复现出你说的那种情况，你本地调试下看看

**Comment by lzk66688** [comment]
> 没复现出你说的那种情况，你本地调试下看看
我就是在本地测试的，一输入中文就秒退，偶尔能输入中文，这个bug是v3那个带弹窗的，
还有个就是另一种方案的vue3写的话，编辑的icon出不来，换成elementplus的标签，点击会报错：chilrenNode找不到，2.清空内容之后失焦，再点击，input框出不来
